---
- name: Add LDAP to PC
  local_action:
    module: uri
    url: "https://{{ pc_new_ip }}:9440/api/nutanix/v3/directory_services"
    method: POST
    url_username: "admin"
    url_password: "{{ new_pc_admin_pw }}"
    validate_certs: no
    return_content: yes
    status_code: 202
    body_format: json
    body: |
      {
          "spec": {
              "name": "{{ ldap_name }}",
              "resources": {
                  "url": "{{ ldap_url }}",
                  "directory_type": "ACTIVE_DIRECTORY",
                  "domain_name": "{{ ldap_domain }}",
                  "service_account": {
                      "username": "{{ ldap_username }}",
                      "password": "{{ ldap_pw }}"
                  }
              }
          },
          "metadata": {
            "kind": "directory_service"
          }
      }
    force_basic_auth: yes
  check_mode: false
  register: result


#- name: Show result of the POST call
#  debug:
#    msg: 
#     - "{{ result }}"
#  check_mode: false
