---
- name: Add LDAP to PC
  local_action:
    module: uri
    url: "https://{{ pc_new_ip }}:9440/api/nutanix/v3/directory_services"
    method: POST
    url_username: "admin"
    url_password: "nx2Tech321!"
    validate_certs: no
    return_content: yes
    status_code: 202
    body_format: json
    body: |
      {
          "spec": {
              "name": "lab",
              "resources": {
                  "url": "ldaps://10.",
                  "directory_type": "ACTIVE_DIRECTORY",
                  "domain_name": "lab.local",
                  "service_account": {
                      "username": "admin@lab.local",
                      "password": "password"
                  }
              }
          },
          "metadata": {
            "kind": "directory_service"
          }
      }
  check_mode: false
  register: result


#- name: Show result of the POST call
#  debug:
#    msg: 
#     - "{{ result }}"
#  check_mode: false
