---
- name: Dynamically add a host (in init_pc_cluster)
  add_host:
    hostname: "{{ pc_new_ip }}"
    ansible_user: "{{ ans_user }}"
    ansible_password: "{{ ans_password }}"
    ansible_connection: ssh

- name: Build the PC cluster
  shell: /usr/local/nutanix/cluster/bin/cluster --cluster_function_list="multicluster" -s {{pc_new_ip}} create
  delegate_to: "{{pc_new_ip}}"
  vars:
    command_timeout: 1200
